### ISSUE TITLE
not plugins fille ?

### ISSUE THREAD

**Issue by minsto** [LavaPowered/Lava#11]
![pas de plugins](https://user-images.githubusercontent.com/3311942/63652335-48c77e00-c72d-11e9-8856-cee41f6e40dc.png)
  Hmmm is normal is not plugins fille spigot fille is here ? thank

**Comment by GMatrixGames** [comment]
Please use this version: https://ci.codemc.org/job/LavaPowered/job/Lava/46/artifact/build/distributions/Lava-git-Lava-8318ed6-server.jar

**Comment by minsto** [comment]
is a problème i send my crash-server 
[crash-2019-08-25_12.11.41-server.txt](https://github.com/LavaPowered/Lava/files/3538332/crash-2019-08-25_12.11.41-server.txt)

**Comment by GMatrixGames** [comment]
If you do not need to keep your world, please remove all files except for eula.txt and the lava server jar

**Comment by minsto** [comment]
is many more mods and plugin is not work
