### ISSUE TITLE
[Plugin] WorldEdit doesn't recognize modded blocks.

### ISSUE THREAD

**Issue by NightScale5755** [LavaPowered/Lava#12]
Example:
When I use Worldedit (Spigot and Forge/Spigot only), the block IDs don't work, and the numeric IDs return an "does not match valid block type" error.
Idk what else to say...

**Comment by GMatrixGames** [comment]
This issue is unable to be fixed on our end, WG and WE needs to add support for extra items and blocks other than vanilla.
