### ISSUE TITLE
OpenComputers Caught Exception

### ISSUE THREAD

**Issue by GGothicRide** [LavaPowered/Lava#13]
[crash-2019-12-30_21.33.45-server.txt](https://github.com/LavaPowered/Lava/files/4011130/crash-2019-12-30_21.33.45-server.txt)

**Comment by GGothicRide** [comment]
Issue Resolved: Migging Files libraries/com/typesafe/config/1.2.1/

**Comment by GMatrixGames** [comment]
Fixed in new libraries update
