### ISSUE TITLE
Lava ForgeNetwork Handler

### ISSUE THREAD

**Issue by GGothicRide** [LavaPowered/Lava#15]
Log File From server anytime a player logs in
Not sure if this is forge itself causing this or Lava so i copied the entire Log from the console
and the log files themselves
[Forge-networkManager - debug.txt](https://github.com/LavaPowered/Lava/files/4011447/Forge-networkManager.-.debug.txt)
[Forge-networkManager.txt](https://github.com/LavaPowered/Lava/files/4011448/Forge-networkManager.txt)

**Comment by GMatrixGames** [comment]
The mod "ingameinfo" is causing this issue. Please report it to the mod author.
