### ISSUE TITLE
MagicSpells/EffectLib Compatibility

### ISSUE THREAD

**Issue by gundom0802** [LavaPowered/Lava#2]
https://github.com/TheComputerGeek2/MagicSpells
https://github.com/Slikey/EffectLib

These 2 plugins don't seem to work. Getting errors. MagicSpells is dependent on EffectLib to work

Error Log:
https://hastebin.com/oxatixezuz.md

**Comment by ca1halman** [comment]
Seems that some plugins don't load deps, fixing soon.

**Comment by GMatrixGames** [comment]
**UPDATE:**

This issue should be solved in the rewrite branch, will be testing when NMS is implemented into the branch
